import type { LucideIcon } from "lucide-react";
import {
  Activity,
  BarChart3,
  Bell,
  Building2,
  Calendar,
  CalendarDays,
  ClipboardCheck,
  ClipboardList,
  Compass,
  Flag,
  Grid2x2,
  Home,
  Landmark,
  LayoutDashboard,
  LifeBuoy,
  Megaphone,
  MessageSquare,
  MessageSquareText,
  Newspaper,
  RotateCcw,
  ScrollText,
  Settings,
  ShieldCheck,
  Trophy,
  User,
  UserCog,
  UserPlus,
  Users,
  Workflow,
  Bookmark,
  Eye,
  FileText,
  PenSquare,
} from "lucide-react";
import type { BottomNavItem } from "@/components/dashboard/MobileBottomNav";
import type { NavItem } from "@/components/dashboard/DashboardLayout";
import type { Role } from "@/lib/auth";

export const ROLE_NAV: Record<Role, NavItem[]> = {
  student: [
    { to: "/student", label: "Home Feed", icon: Home, section: "Student" },
    { to: "/student/explore", label: "Explore", icon: Compass, section: "Student" },
    {
      to: "/student/my-orgs",
      label: "My Organizations",
      icon: Users,
      badge: "3",
      section: "Student",
    },
    { to: "/student/events", label: "Events", icon: Calendar, section: "Student" },
    { to: "/student/saved", label: "Saved", icon: Bookmark, section: "Student" },
    {
      to: "/student/notifications",
      label: "Notifications",
      icon: Bell,
      badge: "4",
      section: "Student",
    },
    {
      to: "/student/messages",
      label: "Messages",
      icon: MessageSquare,
      badge: "2",
      section: "Student",
    },
    { to: "/student/profile", label: "Profile", icon: User, section: "Student" },
    { to: "/student/categories", label: "Categories", icon: Grid2x2, section: "Discover" },
    {
      to: "/student/top-organizations",
      label: "Top Organizations",
      icon: Trophy,
      section: "Discover",
    },
    { to: "/student/top-events", label: "Top Events", icon: CalendarDays, section: "Discover" },
    { to: "/student/help", label: "Help", icon: LifeBuoy, section: "Support" },
    { to: "/student/settings", label: "Settings", icon: Settings, section: "Support" },
  ],
  leader: [
    { to: "/leader", label: "Dashboard", icon: LayoutDashboard, section: "WORKSPACE" },
    { to: "/leader/feed", label: "Organization Feed", icon: Newspaper, section: "WORKSPACE" },
    { to: "/leader/preview", label: "Public Preview", icon: Eye, section: "WORKSPACE" },
    {
      to: "/leader/organization",
      label: "Edit Organization",
      icon: Building2,
      section: "MANAGEMENT",
    },
    { to: "/leader/compliance", label: "Accreditation", icon: ShieldCheck, section: "MANAGEMENT" },
    { to: "/leader/members", label: "Members", icon: Users, section: "MANAGEMENT" },
    {
      to: "/leader/requests",
      label: "Membership Requests",
      icon: UserPlus,
      badge: "12",
      section: "MANAGEMENT",
    },
    { to: "/leader/manage-events", label: "Events", icon: Calendar, section: "MANAGEMENT" },
    { to: "/leader/workflows", label: "Event Workflows", icon: Workflow, section: "MANAGEMENT" },
    { to: "/leader/revisions", label: "Revision Center", icon: RotateCcw, section: "MANAGEMENT" },
    {
      to: "/leader/officer-transition",
      label: "Officer Transition",
      icon: UserCog,
      section: "MANAGEMENT",
    },
    {
      to: "/leader/requirements",
      label: "Event Requirements",
      icon: ClipboardCheck,
      section: "MANAGEMENT",
    },
    { to: "/leader/attendees", label: "Attendees", icon: ClipboardList, section: "MANAGEMENT" },
    { to: "/leader/create-post", label: "Create Post", icon: PenSquare, section: "MANAGEMENT" },
    { to: "/leader/posts", label: "Manage Posts", icon: FileText, section: "MANAGEMENT" },
    {
      to: "/leader/comments",
      label: "Comments",
      icon: MessageSquare,
      badge: "8",
      section: "MANAGEMENT",
    },
    { to: "/leader/notifications", label: "Notifications", icon: Bell, section: "SETTINGS" },
    { to: "/leader/profile", label: "Profile", icon: User, section: "SETTINGS" },
  ],
  adviser: [
    { to: "/adviser", label: "Dashboard", icon: LayoutDashboard, section: "WORKSPACE" },
    {
      to: "/adviser/transitions",
      label: "Officer Transitions",
      icon: UserCog,
      section: "WORKSPACE",
    },
    { to: "/adviser/posts", label: "Post Approvals", icon: Megaphone, section: "WORKSPACE" },
    {
      to: "/adviser/requirements",
      label: "Requirements",
      icon: ClipboardCheck,
      section: "WORKSPACE",
    },
    { to: "/adviser/compliance", label: "Accreditation", icon: ShieldCheck, section: "WORKSPACE" },
    {
      to: "/adviser/review-center",
      label: "Review Center",
      icon: MessageSquareText,
      section: "WORKSPACE",
    },
    { to: "/adviser/analytics", label: "Analytics", icon: BarChart3, section: "WORKSPACE" },
    { to: "/adviser/members", label: "Member activity", icon: Users, section: "WORKSPACE" },
    { to: "/adviser/notifications", label: "Notifications", icon: Bell, section: "REVIEW" },
    { to: "/adviser/profile", label: "Profile", icon: User, section: "SETTINGS" },
  ],
  admin2: [
    { to: "/admin2", label: "Dashboard", icon: LayoutDashboard, section: "OVERVIEW" },
    { to: "/admin2/monitoring", label: "Monitoring", icon: Activity, section: "OVERVIEW" },
    {
      to: "/admin2/review-center",
      label: "Review Center",
      icon: MessageSquareText,
      section: "OVERVIEW",
    },
    { to: "/admin2/compliance", label: "Compliance", icon: ShieldCheck, section: "OVERVIEW" },
    { to: "/admin2/requirements", label: "Requirements", icon: ClipboardCheck, section: "REVIEWS" },
    { to: "/admin2/posts", label: "Post Publishing", icon: Megaphone, section: "REVIEWS" },
    { to: "/admin2/notifications", label: "Notifications", icon: Bell, section: "REVIEWS" },
    { to: "/admin2/profile", label: "Profile", icon: User, section: "SETTINGS" },
  ],
  admin1: [
    { to: "/admin1", label: "Dashboard", icon: LayoutDashboard, section: "OVERVIEW" },
    { to: "/admin1/authority", label: "Final Authority", icon: ShieldCheck, section: "OVERVIEW" },
    { to: "/admin1/organizations", label: "Organizations", icon: Building2, section: "OVERVIEW" },
    { to: "/admin1/accreditation", label: "Accreditation", icon: Landmark, section: "OVERVIEW" },
    { to: "/admin1/requirements", label: "Requirements", icon: ClipboardCheck, section: "OVERVIEW" },
    { to: "/admin1/transitions", label: "Officer Transitions", icon: UserCog, section: "OVERVIEW" },
    { to: "/admin1/governance", label: "Governance", icon: ScrollText, section: "OVERVIEW" },
    { to: "/admin1/notifications", label: "Notifications", icon: Bell, section: "AUTHORITY" },
    { to: "/admin1/profile", label: "Profile", icon: User, section: "SETTINGS" },
  ],
  admin: [
    { to: "/admin", label: "Dashboard", icon: LayoutDashboard, section: "OVERVIEW" },
    { to: "/admin/analytics", label: "Analytics", icon: BarChart3, section: "OVERVIEW" },
    { to: "/admin/reports", label: "Reports", icon: ClipboardList, section: "OVERVIEW" },
    { to: "/admin/users", label: "Users", icon: Users, section: "MANAGEMENT" },
    {
      to: "/admin/organizations",
      label: "Organizations",
      icon: Building2,
      badge: "5",
      section: "MANAGEMENT",
    },
    { to: "/admin/events", label: "Events", icon: Calendar, section: "MANAGEMENT" },
    { to: "/admin/announcements", label: "Announcements", icon: Megaphone, section: "MANAGEMENT" },
    {
      to: "/admin/reported-posts",
      label: "Reported Posts",
      icon: Flag,
      badge: "4",
      section: "MODERATION",
    },
    {
      to: "/admin/reported-comments",
      label: "Reported Comments",
      icon: MessageSquare,
      badge: "5",
      section: "MODERATION",
    },
    { to: "/admin/logs", label: "Activity Logs", icon: ScrollText, section: "MODERATION" },
    { to: "/admin/profile", label: "Profile", icon: User, section: "SETTINGS" },
  ],
};

export const ROLE_BOTTOM_NAV: Partial<Record<Role, BottomNavItem[]>> = {
  student: [
    { to: "/student", label: "Home", icon: Home },
    { to: "/student/explore", label: "Explore", icon: Compass },
    { to: "/student/events", label: "Events", icon: Calendar },
    { to: "/student/notifications", label: "Alerts", icon: Bell, badge: "4" },
    { to: "/student/profile", label: "Me", icon: User },
  ],
  leader: [
    { to: "/leader", label: "Home", icon: LayoutDashboard },
    { to: "/leader/feed", label: "Feed", icon: Newspaper },
    { to: "/leader/revisions", label: "Revisions", icon: RotateCcw },
    { to: "/leader/create-post", label: "Post", icon: PenSquare },
    { to: "/leader/notifications", label: "Alerts", icon: Bell },
  ],
  adviser: [
    { to: "/adviser", label: "Queue", icon: ClipboardCheck },
    { to: "/adviser/review-center", label: "Review", icon: MessageSquareText },
    { to: "/adviser/analytics", label: "Analytics", icon: BarChart3 },
    { to: "/adviser/notifications", label: "Alerts", icon: Bell },
    { to: "/adviser/profile", label: "Me", icon: User },
  ],
  admin2: [
    { to: "/admin2", label: "Queue", icon: ClipboardCheck },
    { to: "/admin2/monitoring", label: "Monitor", icon: Activity },
    { to: "/admin2/review-center", label: "Review", icon: MessageSquareText },
    { to: "/admin2/compliance", label: "Compliance", icon: ShieldCheck },
    { to: "/admin2/profile", label: "Me", icon: User },
  ],
  admin1: [
    { to: "/admin1", label: "Queue", icon: ShieldCheck },
    { to: "/admin1/authority", label: "Authority", icon: Landmark },
    { to: "/admin1/organizations", label: "Orgs", icon: Building2 },
    { to: "/admin1/governance", label: "Records", icon: ScrollText },
    { to: "/admin1/profile", label: "Me", icon: User },
  ],
  admin: [
    { to: "/admin", label: "Home", icon: LayoutDashboard },
    { to: "/admin/analytics", label: "Stats", icon: BarChart3 },
    { to: "/admin/reported-posts", label: "Reports", icon: Flag, badge: "4" },
    { to: "/admin/users", label: "Users", icon: Users },
    { to: "/admin/profile", label: "Me", icon: User },
  ],
};
