/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderRouteImport } from './routes/leader'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as LeaderIndexRouteImport } from './routes/leader.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudentTopOrganizationsRouteImport } from './routes/student.top-organizations'
import { Route as StudentTopEventsRouteImport } from './routes/student.top-events'
import { Route as StudentSettingsRouteImport } from './routes/student.settings'
import { Route as StudentSavedRouteImport } from './routes/student.saved'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentMyOrgsRouteImport } from './routes/student.my-orgs'
import { Route as StudentMessagesRouteImport } from './routes/student.messages'
import { Route as StudentHelpRouteImport } from './routes/student.help'
import { Route as StudentExploreRouteImport } from './routes/student.explore'
import { Route as StudentEventsRouteImport } from './routes/student.events'
import { Route as StudentCategoriesRouteImport } from './routes/student.categories'
import { Route as OrgSlugRouteImport } from './routes/org.$slug'
import { Route as LeaderRequestsRouteImport } from './routes/leader.requests'
import { Route as LeaderProfileRouteImport } from './routes/leader.profile'
import { Route as LeaderPreviewRouteImport } from './routes/leader.preview'
import { Route as LeaderPostsRouteImport } from './routes/leader.posts'
import { Route as LeaderOrganizationRouteImport } from './routes/leader.organization'
import { Route as LeaderMembersRouteImport } from './routes/leader.members'
import { Route as LeaderManageEventsRouteImport } from './routes/leader.manage-events'
import { Route as LeaderFeedRouteImport } from './routes/leader.feed'
import { Route as LeaderCreatePostRouteImport } from './routes/leader.create-post'
import { Route as LeaderCreateEventRouteImport } from './routes/leader.create-event'
import { Route as LeaderCommentsRouteImport } from './routes/leader.comments'
import { Route as LeaderAttendeesRouteImport } from './routes/leader.attendees'
import { Route as LeaderAttendanceRouteImport } from './routes/leader.attendance'
import { Route as LeaderAnnouncementsRouteImport } from './routes/leader.announcements'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminReportedPostsRouteImport } from './routes/admin.reported-posts'
import { Route as AdminReportedCommentsRouteImport } from './routes/admin.reported-comments'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminOrganizationsRouteImport } from './routes/admin.organizations'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as StudentOrgSlugRouteImport } from './routes/student.org.$slug'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderRoute = LeaderRouteImport.update({
  id: '/leader',
  path: '/leader',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const LeaderIndexRoute = LeaderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeaderRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentTopOrganizationsRoute = StudentTopOrganizationsRouteImport.update({
  id: '/top-organizations',
  path: '/top-organizations',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTopEventsRoute = StudentTopEventsRouteImport.update({
  id: '/top-events',
  path: '/top-events',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSettingsRoute = StudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSavedRoute = StudentSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMyOrgsRoute = StudentMyOrgsRouteImport.update({
  id: '/my-orgs',
  path: '/my-orgs',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMessagesRoute = StudentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHelpRoute = StudentHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => StudentRoute,
} as any)
const StudentExploreRoute = StudentExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => StudentRoute,
} as any)
const StudentEventsRoute = StudentEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCategoriesRoute = StudentCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => StudentRoute,
} as any)
const OrgSlugRoute = OrgSlugRouteImport.update({
  id: '/org/$slug',
  path: '/org/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderRequestsRoute = LeaderRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => LeaderRoute,
} as any)
const LeaderProfileRoute = LeaderProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LeaderRoute,
} as any)
const LeaderPreviewRoute = LeaderPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => LeaderRoute,
} as any)
const LeaderPostsRoute = LeaderPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => LeaderRoute,
} as any)
const LeaderOrganizationRoute = LeaderOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => LeaderRoute,
} as any)
const LeaderMembersRoute = LeaderMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => LeaderRoute,
} as any)
const LeaderManageEventsRoute = LeaderManageEventsRouteImport.update({
  id: '/manage-events',
  path: '/manage-events',
  getParentRoute: () => LeaderRoute,
} as any)
const LeaderFeedRoute = LeaderFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => LeaderRoute,
} as any)
const LeaderCreatePostRoute = LeaderCreatePostRouteImport.update({
  id: '/create-post',
  path: '/create-post',
  getParentRoute: () => LeaderRoute,
} as any)
const LeaderCreateEventRoute = LeaderCreateEventRouteImport.update({
  id: '/create-event',
  path: '/create-event',
  getParentRoute: () => LeaderRoute,
} as any)
const LeaderCommentsRoute = LeaderCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => LeaderRoute,
} as any)
const LeaderAttendeesRoute = LeaderAttendeesRouteImport.update({
  id: '/attendees',
  path: '/attendees',
  getParentRoute: () => LeaderRoute,
} as any)
const LeaderAttendanceRoute = LeaderAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => LeaderRoute,
} as any)
const LeaderAnnouncementsRoute = LeaderAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => LeaderRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportedPostsRoute = AdminReportedPostsRouteImport.update({
  id: '/reported-posts',
  path: '/reported-posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportedCommentsRoute = AdminReportedCommentsRouteImport.update({
  id: '/reported-comments',
  path: '/reported-comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const StudentOrgSlugRoute = StudentOrgSlugRouteImport.update({
  id: '/org/$slug',
  path: '/org/$slug',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/events': typeof EventsRoute
  '/features': typeof FeaturesRoute
  '/leader': typeof LeaderRouteWithChildren
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reported-comments': typeof AdminReportedCommentsRoute
  '/admin/reported-posts': typeof AdminReportedPostsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/leader/announcements': typeof LeaderAnnouncementsRoute
  '/leader/attendance': typeof LeaderAttendanceRoute
  '/leader/attendees': typeof LeaderAttendeesRoute
  '/leader/comments': typeof LeaderCommentsRoute
  '/leader/create-event': typeof LeaderCreateEventRoute
  '/leader/create-post': typeof LeaderCreatePostRoute
  '/leader/feed': typeof LeaderFeedRoute
  '/leader/manage-events': typeof LeaderManageEventsRoute
  '/leader/members': typeof LeaderMembersRoute
  '/leader/organization': typeof LeaderOrganizationRoute
  '/leader/posts': typeof LeaderPostsRoute
  '/leader/preview': typeof LeaderPreviewRoute
  '/leader/profile': typeof LeaderProfileRoute
  '/leader/requests': typeof LeaderRequestsRoute
  '/org/$slug': typeof OrgSlugRoute
  '/student/categories': typeof StudentCategoriesRoute
  '/student/events': typeof StudentEventsRoute
  '/student/explore': typeof StudentExploreRoute
  '/student/help': typeof StudentHelpRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/my-orgs': typeof StudentMyOrgsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/saved': typeof StudentSavedRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/top-events': typeof StudentTopEventsRoute
  '/student/top-organizations': typeof StudentTopOrganizationsRoute
  '/admin/': typeof AdminIndexRoute
  '/leader/': typeof LeaderIndexRoute
  '/student/': typeof StudentIndexRoute
  '/student/org/$slug': typeof StudentOrgSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/events': typeof EventsRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reported-comments': typeof AdminReportedCommentsRoute
  '/admin/reported-posts': typeof AdminReportedPostsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/leader/announcements': typeof LeaderAnnouncementsRoute
  '/leader/attendance': typeof LeaderAttendanceRoute
  '/leader/attendees': typeof LeaderAttendeesRoute
  '/leader/comments': typeof LeaderCommentsRoute
  '/leader/create-event': typeof LeaderCreateEventRoute
  '/leader/create-post': typeof LeaderCreatePostRoute
  '/leader/feed': typeof LeaderFeedRoute
  '/leader/manage-events': typeof LeaderManageEventsRoute
  '/leader/members': typeof LeaderMembersRoute
  '/leader/organization': typeof LeaderOrganizationRoute
  '/leader/posts': typeof LeaderPostsRoute
  '/leader/preview': typeof LeaderPreviewRoute
  '/leader/profile': typeof LeaderProfileRoute
  '/leader/requests': typeof LeaderRequestsRoute
  '/org/$slug': typeof OrgSlugRoute
  '/student/categories': typeof StudentCategoriesRoute
  '/student/events': typeof StudentEventsRoute
  '/student/explore': typeof StudentExploreRoute
  '/student/help': typeof StudentHelpRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/my-orgs': typeof StudentMyOrgsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/saved': typeof StudentSavedRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/top-events': typeof StudentTopEventsRoute
  '/student/top-organizations': typeof StudentTopOrganizationsRoute
  '/admin': typeof AdminIndexRoute
  '/leader': typeof LeaderIndexRoute
  '/student': typeof StudentIndexRoute
  '/student/org/$slug': typeof StudentOrgSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/events': typeof EventsRoute
  '/features': typeof FeaturesRoute
  '/leader': typeof LeaderRouteWithChildren
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reported-comments': typeof AdminReportedCommentsRoute
  '/admin/reported-posts': typeof AdminReportedPostsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/leader/announcements': typeof LeaderAnnouncementsRoute
  '/leader/attendance': typeof LeaderAttendanceRoute
  '/leader/attendees': typeof LeaderAttendeesRoute
  '/leader/comments': typeof LeaderCommentsRoute
  '/leader/create-event': typeof LeaderCreateEventRoute
  '/leader/create-post': typeof LeaderCreatePostRoute
  '/leader/feed': typeof LeaderFeedRoute
  '/leader/manage-events': typeof LeaderManageEventsRoute
  '/leader/members': typeof LeaderMembersRoute
  '/leader/organization': typeof LeaderOrganizationRoute
  '/leader/posts': typeof LeaderPostsRoute
  '/leader/preview': typeof LeaderPreviewRoute
  '/leader/profile': typeof LeaderProfileRoute
  '/leader/requests': typeof LeaderRequestsRoute
  '/org/$slug': typeof OrgSlugRoute
  '/student/categories': typeof StudentCategoriesRoute
  '/student/events': typeof StudentEventsRoute
  '/student/explore': typeof StudentExploreRoute
  '/student/help': typeof StudentHelpRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/my-orgs': typeof StudentMyOrgsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/saved': typeof StudentSavedRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/top-events': typeof StudentTopEventsRoute
  '/student/top-organizations': typeof StudentTopOrganizationsRoute
  '/admin/': typeof AdminIndexRoute
  '/leader/': typeof LeaderIndexRoute
  '/student/': typeof StudentIndexRoute
  '/student/org/$slug': typeof StudentOrgSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/events'
    | '/features'
    | '/leader'
    | '/login'
    | '/organizations'
    | '/register'
    | '/student'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/events'
    | '/admin/logs'
    | '/admin/moderation'
    | '/admin/organizations'
    | '/admin/profile'
    | '/admin/reported-comments'
    | '/admin/reported-posts'
    | '/admin/reports'
    | '/admin/users'
    | '/leader/announcements'
    | '/leader/attendance'
    | '/leader/attendees'
    | '/leader/comments'
    | '/leader/create-event'
    | '/leader/create-post'
    | '/leader/feed'
    | '/leader/manage-events'
    | '/leader/members'
    | '/leader/organization'
    | '/leader/posts'
    | '/leader/preview'
    | '/leader/profile'
    | '/leader/requests'
    | '/org/$slug'
    | '/student/categories'
    | '/student/events'
    | '/student/explore'
    | '/student/help'
    | '/student/messages'
    | '/student/my-orgs'
    | '/student/notifications'
    | '/student/profile'
    | '/student/saved'
    | '/student/settings'
    | '/student/top-events'
    | '/student/top-organizations'
    | '/admin/'
    | '/leader/'
    | '/student/'
    | '/student/org/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/events'
    | '/features'
    | '/login'
    | '/organizations'
    | '/register'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/events'
    | '/admin/logs'
    | '/admin/moderation'
    | '/admin/organizations'
    | '/admin/profile'
    | '/admin/reported-comments'
    | '/admin/reported-posts'
    | '/admin/reports'
    | '/admin/users'
    | '/leader/announcements'
    | '/leader/attendance'
    | '/leader/attendees'
    | '/leader/comments'
    | '/leader/create-event'
    | '/leader/create-post'
    | '/leader/feed'
    | '/leader/manage-events'
    | '/leader/members'
    | '/leader/organization'
    | '/leader/posts'
    | '/leader/preview'
    | '/leader/profile'
    | '/leader/requests'
    | '/org/$slug'
    | '/student/categories'
    | '/student/events'
    | '/student/explore'
    | '/student/help'
    | '/student/messages'
    | '/student/my-orgs'
    | '/student/notifications'
    | '/student/profile'
    | '/student/saved'
    | '/student/settings'
    | '/student/top-events'
    | '/student/top-organizations'
    | '/admin'
    | '/leader'
    | '/student'
    | '/student/org/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/events'
    | '/features'
    | '/leader'
    | '/login'
    | '/organizations'
    | '/register'
    | '/student'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/events'
    | '/admin/logs'
    | '/admin/moderation'
    | '/admin/organizations'
    | '/admin/profile'
    | '/admin/reported-comments'
    | '/admin/reported-posts'
    | '/admin/reports'
    | '/admin/users'
    | '/leader/announcements'
    | '/leader/attendance'
    | '/leader/attendees'
    | '/leader/comments'
    | '/leader/create-event'
    | '/leader/create-post'
    | '/leader/feed'
    | '/leader/manage-events'
    | '/leader/members'
    | '/leader/organization'
    | '/leader/posts'
    | '/leader/preview'
    | '/leader/profile'
    | '/leader/requests'
    | '/org/$slug'
    | '/student/categories'
    | '/student/events'
    | '/student/explore'
    | '/student/help'
    | '/student/messages'
    | '/student/my-orgs'
    | '/student/notifications'
    | '/student/profile'
    | '/student/saved'
    | '/student/settings'
    | '/student/top-events'
    | '/student/top-organizations'
    | '/admin/'
    | '/leader/'
    | '/student/'
    | '/student/org/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  EventsRoute: typeof EventsRoute
  FeaturesRoute: typeof FeaturesRoute
  LeaderRoute: typeof LeaderRouteWithChildren
  LoginRoute: typeof LoginRoute
  OrganizationsRoute: typeof OrganizationsRoute
  RegisterRoute: typeof RegisterRoute
  StudentRoute: typeof StudentRouteWithChildren
  OrgSlugRoute: typeof OrgSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leader': {
      id: '/leader'
      path: '/leader'
      fullPath: '/leader'
      preLoaderRoute: typeof LeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/leader/': {
      id: '/leader/'
      path: '/'
      fullPath: '/leader/'
      preLoaderRoute: typeof LeaderIndexRouteImport
      parentRoute: typeof LeaderRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/top-organizations': {
      id: '/student/top-organizations'
      path: '/top-organizations'
      fullPath: '/student/top-organizations'
      preLoaderRoute: typeof StudentTopOrganizationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/top-events': {
      id: '/student/top-events'
      path: '/top-events'
      fullPath: '/student/top-events'
      preLoaderRoute: typeof StudentTopEventsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/settings': {
      id: '/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof StudentSettingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/saved': {
      id: '/student/saved'
      path: '/saved'
      fullPath: '/student/saved'
      preLoaderRoute: typeof StudentSavedRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/my-orgs': {
      id: '/student/my-orgs'
      path: '/my-orgs'
      fullPath: '/student/my-orgs'
      preLoaderRoute: typeof StudentMyOrgsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/messages': {
      id: '/student/messages'
      path: '/messages'
      fullPath: '/student/messages'
      preLoaderRoute: typeof StudentMessagesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/help': {
      id: '/student/help'
      path: '/help'
      fullPath: '/student/help'
      preLoaderRoute: typeof StudentHelpRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/explore': {
      id: '/student/explore'
      path: '/explore'
      fullPath: '/student/explore'
      preLoaderRoute: typeof StudentExploreRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/events': {
      id: '/student/events'
      path: '/events'
      fullPath: '/student/events'
      preLoaderRoute: typeof StudentEventsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/categories': {
      id: '/student/categories'
      path: '/categories'
      fullPath: '/student/categories'
      preLoaderRoute: typeof StudentCategoriesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/org/$slug': {
      id: '/org/$slug'
      path: '/org/$slug'
      fullPath: '/org/$slug'
      preLoaderRoute: typeof OrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leader/requests': {
      id: '/leader/requests'
      path: '/requests'
      fullPath: '/leader/requests'
      preLoaderRoute: typeof LeaderRequestsRouteImport
      parentRoute: typeof LeaderRoute
    }
    '/leader/profile': {
      id: '/leader/profile'
      path: '/profile'
      fullPath: '/leader/profile'
      preLoaderRoute: typeof LeaderProfileRouteImport
      parentRoute: typeof LeaderRoute
    }
    '/leader/preview': {
      id: '/leader/preview'
      path: '/preview'
      fullPath: '/leader/preview'
      preLoaderRoute: typeof LeaderPreviewRouteImport
      parentRoute: typeof LeaderRoute
    }
    '/leader/posts': {
      id: '/leader/posts'
      path: '/posts'
      fullPath: '/leader/posts'
      preLoaderRoute: typeof LeaderPostsRouteImport
      parentRoute: typeof LeaderRoute
    }
    '/leader/organization': {
      id: '/leader/organization'
      path: '/organization'
      fullPath: '/leader/organization'
      preLoaderRoute: typeof LeaderOrganizationRouteImport
      parentRoute: typeof LeaderRoute
    }
    '/leader/members': {
      id: '/leader/members'
      path: '/members'
      fullPath: '/leader/members'
      preLoaderRoute: typeof LeaderMembersRouteImport
      parentRoute: typeof LeaderRoute
    }
    '/leader/manage-events': {
      id: '/leader/manage-events'
      path: '/manage-events'
      fullPath: '/leader/manage-events'
      preLoaderRoute: typeof LeaderManageEventsRouteImport
      parentRoute: typeof LeaderRoute
    }
    '/leader/feed': {
      id: '/leader/feed'
      path: '/feed'
      fullPath: '/leader/feed'
      preLoaderRoute: typeof LeaderFeedRouteImport
      parentRoute: typeof LeaderRoute
    }
    '/leader/create-post': {
      id: '/leader/create-post'
      path: '/create-post'
      fullPath: '/leader/create-post'
      preLoaderRoute: typeof LeaderCreatePostRouteImport
      parentRoute: typeof LeaderRoute
    }
    '/leader/create-event': {
      id: '/leader/create-event'
      path: '/create-event'
      fullPath: '/leader/create-event'
      preLoaderRoute: typeof LeaderCreateEventRouteImport
      parentRoute: typeof LeaderRoute
    }
    '/leader/comments': {
      id: '/leader/comments'
      path: '/comments'
      fullPath: '/leader/comments'
      preLoaderRoute: typeof LeaderCommentsRouteImport
      parentRoute: typeof LeaderRoute
    }
    '/leader/attendees': {
      id: '/leader/attendees'
      path: '/attendees'
      fullPath: '/leader/attendees'
      preLoaderRoute: typeof LeaderAttendeesRouteImport
      parentRoute: typeof LeaderRoute
    }
    '/leader/attendance': {
      id: '/leader/attendance'
      path: '/attendance'
      fullPath: '/leader/attendance'
      preLoaderRoute: typeof LeaderAttendanceRouteImport
      parentRoute: typeof LeaderRoute
    }
    '/leader/announcements': {
      id: '/leader/announcements'
      path: '/announcements'
      fullPath: '/leader/announcements'
      preLoaderRoute: typeof LeaderAnnouncementsRouteImport
      parentRoute: typeof LeaderRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reported-posts': {
      id: '/admin/reported-posts'
      path: '/reported-posts'
      fullPath: '/admin/reported-posts'
      preLoaderRoute: typeof AdminReportedPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reported-comments': {
      id: '/admin/reported-comments'
      path: '/reported-comments'
      fullPath: '/admin/reported-comments'
      preLoaderRoute: typeof AdminReportedCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/org/$slug': {
      id: '/student/org/$slug'
      path: '/org/$slug'
      fullPath: '/student/org/$slug'
      preLoaderRoute: typeof StudentOrgSlugRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReportedCommentsRoute: typeof AdminReportedCommentsRoute
  AdminReportedPostsRoute: typeof AdminReportedPostsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReportedCommentsRoute: AdminReportedCommentsRoute,
  AdminReportedPostsRoute: AdminReportedPostsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LeaderRouteChildren {
  LeaderAnnouncementsRoute: typeof LeaderAnnouncementsRoute
  LeaderAttendanceRoute: typeof LeaderAttendanceRoute
  LeaderAttendeesRoute: typeof LeaderAttendeesRoute
  LeaderCommentsRoute: typeof LeaderCommentsRoute
  LeaderCreateEventRoute: typeof LeaderCreateEventRoute
  LeaderCreatePostRoute: typeof LeaderCreatePostRoute
  LeaderFeedRoute: typeof LeaderFeedRoute
  LeaderManageEventsRoute: typeof LeaderManageEventsRoute
  LeaderMembersRoute: typeof LeaderMembersRoute
  LeaderOrganizationRoute: typeof LeaderOrganizationRoute
  LeaderPostsRoute: typeof LeaderPostsRoute
  LeaderPreviewRoute: typeof LeaderPreviewRoute
  LeaderProfileRoute: typeof LeaderProfileRoute
  LeaderRequestsRoute: typeof LeaderRequestsRoute
  LeaderIndexRoute: typeof LeaderIndexRoute
}

const LeaderRouteChildren: LeaderRouteChildren = {
  LeaderAnnouncementsRoute: LeaderAnnouncementsRoute,
  LeaderAttendanceRoute: LeaderAttendanceRoute,
  LeaderAttendeesRoute: LeaderAttendeesRoute,
  LeaderCommentsRoute: LeaderCommentsRoute,
  LeaderCreateEventRoute: LeaderCreateEventRoute,
  LeaderCreatePostRoute: LeaderCreatePostRoute,
  LeaderFeedRoute: LeaderFeedRoute,
  LeaderManageEventsRoute: LeaderManageEventsRoute,
  LeaderMembersRoute: LeaderMembersRoute,
  LeaderOrganizationRoute: LeaderOrganizationRoute,
  LeaderPostsRoute: LeaderPostsRoute,
  LeaderPreviewRoute: LeaderPreviewRoute,
  LeaderProfileRoute: LeaderProfileRoute,
  LeaderRequestsRoute: LeaderRequestsRoute,
  LeaderIndexRoute: LeaderIndexRoute,
}

const LeaderRouteWithChildren =
  LeaderRoute._addFileChildren(LeaderRouteChildren)

interface StudentRouteChildren {
  StudentCategoriesRoute: typeof StudentCategoriesRoute
  StudentEventsRoute: typeof StudentEventsRoute
  StudentExploreRoute: typeof StudentExploreRoute
  StudentHelpRoute: typeof StudentHelpRoute
  StudentMessagesRoute: typeof StudentMessagesRoute
  StudentMyOrgsRoute: typeof StudentMyOrgsRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentSavedRoute: typeof StudentSavedRoute
  StudentSettingsRoute: typeof StudentSettingsRoute
  StudentTopEventsRoute: typeof StudentTopEventsRoute
  StudentTopOrganizationsRoute: typeof StudentTopOrganizationsRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentOrgSlugRoute: typeof StudentOrgSlugRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCategoriesRoute: StudentCategoriesRoute,
  StudentEventsRoute: StudentEventsRoute,
  StudentExploreRoute: StudentExploreRoute,
  StudentHelpRoute: StudentHelpRoute,
  StudentMessagesRoute: StudentMessagesRoute,
  StudentMyOrgsRoute: StudentMyOrgsRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentSavedRoute: StudentSavedRoute,
  StudentSettingsRoute: StudentSettingsRoute,
  StudentTopEventsRoute: StudentTopEventsRoute,
  StudentTopOrganizationsRoute: StudentTopOrganizationsRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentOrgSlugRoute: StudentOrgSlugRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  EventsRoute: EventsRoute,
  FeaturesRoute: FeaturesRoute,
  LeaderRoute: LeaderRouteWithChildren,
  LoginRoute: LoginRoute,
  OrganizationsRoute: OrganizationsRoute,
  RegisterRoute: RegisterRoute,
  StudentRoute: StudentRouteWithChildren,
  OrgSlugRoute: OrgSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
